app:
  env: local
  debug: true

server:
  http:
    host:
    port: 1424
    timeout: 30s

logger:
  level: debug
  format: console
  output: stdout

database:
  mysql:
    host: service-mysql
    port: 3306
    database: aklht_apartment
    username: root
    password: 8000
    timezone: Local
    parseTime: true
    maxIdleConns: 5
    maxOpenConns: 100
    connMaxLifetime: 120

  redis:
    host: apartment_redis
    port: 6379
    password: ''
    db: 0
    poolSize: 12000
    minIdleConns: 2
    poolTimeout: 60

  elasticSearch:
    addresses:
      - http://apartment_elasticsearch:9200
    username: 'elastic'
    password: '8000'
    enableLogging: true

jwt:
  access_secret: "ACCESS_TOKEN_SECRET"
  refresh_secret: "REFRESH_TOKEN_SECRET"
  access_expire: 168h
  refresh_expire: 720h
  token_type: Bearer

auth:
  google:
    client_id:
    client_secret:
    callback_url:

cloudinary:
  cloud_name:
  api_key:
  api_secret: