extends: base
app:
  env: qc

logger:
  format: json

database:
  mysql:
    host: 1.1.1.1
    #host: localhost
  elasticSearch:
    addresses:
      - http://1.1.1.1:9200
      #- http://localhost:9200
    enableLogging: false